language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests/
  allow_failures:
  - script: pytest --cov=./tests/
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: TwrjVEYtiILANK8YkZZEEK6xSSkAwLbjr1DlkNod1W/Faw7TbeNV7h/ltQWfje2D8Z/PL4K/QLiTi5okAXwXn6Y4rJWg2NJVk07u1DIpkUjtxAwJstqca2weFRUCkiw6v/lh++9NTbFsFbW843anRtwSkdfPpKS3IwQTIBq2Iw/ZtzB34M1lVlrEfGSRW14qQmlIUtEBz9bMD2mkU3HmEtjUrlw5RXAhB0OgDsshdG5cxkqW7myrU+ZmJ3DFuJ4xebve7xIrAf7oBbzbbJWOJHqxr0Bi8TBzFpU9kSk1GcUYqVDCLKboR0+EQSQxBV/sbdxk5Cmt4ldkZGD2Kve9qglRGHlNiJDSql2ZE2Y0kQCTc8MFrWajx2f6BFLxpt+3vRZT52cfFSW+pBK2MULLdbTwstTkHGqoq8IAbHkbgbqrqlOIYMU4P/iYXof6TS1CmZcUGtuHkv4JG9pJnNGCCtYv36l0xg2eqti2ncpjqAkONwNPNiZweybhPhVBwYm7sKJCditUoNLyV3/Vz7ZYZuokJfC1IThhNNMdkrDrxBaFbp64txKv3JzOTo5L34YnnH2xexhcn84cKv2aHTG62FkO4005D16syS3ycO+Bg3NVafPAZN/DTXQkvJvyDCB4L1/zDdk9eKPurO+gAu2UZBmeZJ2qBXML98LPuuI/Ezg=
  app:
    master: stella-app-dp
    dev: stella-app-dp-dev
env:
  global:
  - secure: LOCar7CyVd2PcAKlJwgEKk6XaxfEUx4Ctlman9dMJqUJ+DZ2oYBnAmkYqs+3XWpN1l0lw2IhrwMohs/VmizSCk4Z0JVw6MJ7SQ8fHepBB6bSLgsBUkj6O8iYHyVynHmF/A+wAEDB+34wPy/PsEkZEVYKPpR+/+QyIhRi1F0kNA7WJ/Uvr8pLr0yiNeq3Q9MMQb6GJOOz1GvkN3yR9Ieulv02OpGr6D+ljtpVUU20uKRkHs34mg9LAqF96YJOAoKkvgaB5isNHH46lucqXLm3wTwmk0hlxvb1I1WjO20lGKlHIlTF2XjMt40A9hlLT9xtyjAnNstxPV3ciDbXfTWnV03RU6vHetNiAgJ6zd9soy96pa5ySq2XqV+L1HqR3nOFnNdCjZHRqNAValI1BzbP1iU6KAx3ltxYyeUWDxJ2YbSlr3cYWudA61wc4M0Se6KJ8PCftPZduRE0VdVJXGpEfbZJIPp/6rKh8A+WN6rrOeojdCCwqjHNySg8Qt6bS5v1qWMBgpMNutHLbhvyCmP9uCMQvUUEI8izTTtviP8F3KeT4ZIW6o0HEY0w8QQI63cCdgCiJo6wNrhQrLX4z+U4O+Su3Ab6rbGmqhUQewBKaVYE3mRhS6lnVQr2JP2AYIhITVUf8b5r9/Hdco0EflkSc5getqkEaZHmFdUsoAwet3k=
  - secure: dshNAiwshWvgrQsJtCuCY5JKymw7zXLmfeuWa0viLqFUqfU04j7ckBd6QKsyV1nliNuGL6hw+xWsm+dBGLnTsE/wDRx7+avXc2DAHv+Sak4Md5qGOWuUkSyHNY+ijJGlJs+wmnFInXolbITF+bK77/7fi8IzhcU6Tg/IfH3JEQt+u6sGFG8TobwhsMW9yUKe5/OiQtOfpeBkHKLzUT2i5Ehcy7ikwmVHP8So0z6gmS7v7b0Q7b25o3V5I4XbQm2jPnPyZoPS4I5ICmbnKaZmRUltnrUZ/2KI8TJflvpUinB0F2D+coxmKyrhMLn/iSQ4M47KBj3YjhHICc2yyc39y0iB5AqoMNO6mxFYEEMNoVlR5qLwIZ4CpxtKHoY7BD9QRf62dNLA/j0uUonSIsVfdyluO2QcCdz1Mmslnt/nw+K8zIJzhxz9BlIWFKWQgZcNzBv/ilEu2gWrB4CYpNGc4GZCLkY/hrIWNVE3PDoSbhAu7UH9iSfmkCjfTkFoTFV5wxuPFKj06IvlQoRM2ILiDyPm9+OMdvJCBxVLsk5Rnhi0kxwsASOnvvIs0J+HV4CFu8E4/lOm9DdAilc/afZI0muegBldY/Z7qqlhsrv2BQznGnGhNmz05vREORBq2BI2uCMOxWbA0+f8W9061qFoHdnaT+LbQv2FmDNtkSV6vvE=
