language: python
python: 3.7
dist: xenial
sudo: true
install:
  - pip install pipenv
  - pipenv install --dev
  - pip install pytest-cov 
matrix:
  include:
    - script: pytest --cov=./tests/
  allow_failures:
    - script: pytest --cov=./tests/
notifications:
  email:
    on_success: never
    on_failure: change
