language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests/unit ./tests/unit
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  app:
    master: stella-app-dp
    dev: stella-app-dp-dev
  api_key:
    secure: ACn/gNzWTLxERhpipnu7nHFFcct0nvsvIas+0S9mG9ZkKKDgjr6U4a7/YgOthkh6HPVMzBkYxdaCK3sJWy4g5j78VTxlYEWp7YB2agl3+TaswzfclGC+ojHiYMvbQouu+C1sLnXI0b9Bc81qImZDyv5a1jQxjv3TM9acf2WgKHPsisAyRUxbMcC0Ym+PKYcGkNhIJG1nLVXgqE8ZHARMrtLQ/jjlwpFmf2UGNQ/oyWze7zbIo4BEfmhyyo90QLOa9myXO8M+6DX7uLvk1U6HaQSr/4xXEQwaXN5nPDFrsFx2PRgah619lKrskD0ZYQrltOJ0ybznwrlo4zdmbXnkSJ5Vr24MxQzZ8bz3k5lVDuy1k6zw6Frjw4fcslFeO0NQzp8/WYsiLumfPeW/S2K4VsmJmYlGH2gfQBUo8tGLrPDAm/6jSjWnLxaCaxg2b7W2HblXAI1ML8UxnFq2QAH2p0Snlumcs75DRGlpDQ0Laqy9678QAd216OFI3FM9i/NMXmfyyZOxM7zNWDnjl28xxYha1PP3ZJB/iCcvVVUTghCIwVT/AUTjFszz1L78mBmhYE5vTAV0/+62aVVQb7pbbrh6l1TnbcUOGZStdtSIz0ZkTWXRYMXSrnjY+zWRW0eFxwu6EHsCTqR9P2HlZOqdOs2ycBHL4QawaE3fIpy0gh0=
