language: python
python: 3.7.2
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov-report term-missing --cov-config .coveragerc --cov=./ ./tests/unit
  - script: pytest --cov-report term-missing --cov-config .coveragerc --cov=./ ./tests/integration
notifications:
  email:
    on_success: never
    on_failure: change
before_install:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then openssl aes-256-cbc -K $encrypted_3256ad516826_key -iv $encrypted_3256ad516826_iv
  -in deploy_key.enc -out ~/deploy_key -d; fi
before_deploy:
- bash docker_push
deploy:
  provider: script
  script:  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash deploy; fi
  on:
    branch: dev
