language: python
python: 3.7
dist: xenial
sudo: true
install:
- pip install pipenv
- pipenv install --dev
- pip install pytest-cov
matrix:
  include:
  - script: pytest --cov=./tests/unit ./tests/unit
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
  - secure: LOCar7CyVd2PcAKlJwgEKk6XaxfEUx4Ctlman9dMJqUJ+DZ2oYBnAmkYqs+3XWpN1l0lw2IhrwMohs/VmizSCk4Z0JVw6MJ7SQ8fHepBB6bSLgsBUkj6O8iYHyVynHmF/A+wAEDB+34wPy/PsEkZEVYKPpR+/+QyIhRi1F0kNA7WJ/Uvr8pLr0yiNeq3Q9MMQb6GJOOz1GvkN3yR9Ieulv02OpGr6D+ljtpVUU20uKRkHs34mg9LAqF96YJOAoKkvgaB5isNHH46lucqXLm3wTwmk0hlxvb1I1WjO20lGKlHIlTF2XjMt40A9hlLT9xtyjAnNstxPV3ciDbXfTWnV03RU6vHetNiAgJ6zd9soy96pa5ySq2XqV+L1HqR3nOFnNdCjZHRqNAValI1BzbP1iU6KAx3ltxYyeUWDxJ2YbSlr3cYWudA61wc4M0Se6KJ8PCftPZduRE0VdVJXGpEfbZJIPp/6rKh8A+WN6rrOeojdCCwqjHNySg8Qt6bS5v1qWMBgpMNutHLbhvyCmP9uCMQvUUEI8izTTtviP8F3KeT4ZIW6o0HEY0w8QQI63cCdgCiJo6wNrhQrLX4z+U4O+Su3Ab6rbGmqhUQewBKaVYE3mRhS6lnVQr2JP2AYIhITVUf8b5r9/Hdco0EflkSc5getqkEaZHmFdUsoAwet3k=
  - secure: dshNAiwshWvgrQsJtCuCY5JKymw7zXLmfeuWa0viLqFUqfU04j7ckBd6QKsyV1nliNuGL6hw+xWsm+dBGLnTsE/wDRx7+avXc2DAHv+Sak4Md5qGOWuUkSyHNY+ijJGlJs+wmnFInXolbITF+bK77/7fi8IzhcU6Tg/IfH3JEQt+u6sGFG8TobwhsMW9yUKe5/OiQtOfpeBkHKLzUT2i5Ehcy7ikwmVHP8So0z6gmS7v7b0Q7b25o3V5I4XbQm2jPnPyZoPS4I5ICmbnKaZmRUltnrUZ/2KI8TJflvpUinB0F2D+coxmKyrhMLn/iSQ4M47KBj3YjhHICc2yyc39y0iB5AqoMNO6mxFYEEMNoVlR5qLwIZ4CpxtKHoY7BD9QRf62dNLA/j0uUonSIsVfdyluO2QcCdz1Mmslnt/nw+K8zIJzhxz9BlIWFKWQgZcNzBv/ilEu2gWrB4CYpNGc4GZCLkY/hrIWNVE3PDoSbhAu7UH9iSfmkCjfTkFoTFV5wxuPFKj06IvlQoRM2ILiDyPm9+OMdvJCBxVLsk5Rnhi0kxwsASOnvvIs0J+HV4CFu8E4/lOm9DdAilc/afZI0muegBldY/Z7qqlhsrv2BQznGnGhNmz05vREORBq2BI2uCMOxWbA0+f8W9061qFoHdnaT+LbQv2FmDNtkSV6vvE=
deploy:
  provider: heroku
  app: test-app655312
  on:
    all_branches: true
  app:
    master: stella-app-dp
    production: stella-app-dp-dev
  api_key:
    secure: ACn/gNzWTLxERhpipnu7nHFFcct0nvsvIas+0S9mG9ZkKKDgjr6U4a7/YgOthkh6HPVMzBkYxdaCK3sJWy4g5j78VTxlYEWp7YB2agl3+TaswzfclGC+ojHiYMvbQouu+C1sLnXI0b9Bc81qImZDyv5a1jQxjv3TM9acf2WgKHPsisAyRUxbMcC0Ym+PKYcGkNhIJG1nLVXgqE8ZHARMrtLQ/jjlwpFmf2UGNQ/oyWze7zbIo4BEfmhyyo90QLOa9myXO8M+6DX7uLvk1U6HaQSr/4xXEQwaXN5nPDFrsFx2PRgah619lKrskD0ZYQrltOJ0ybznwrlo4zdmbXnkSJ5Vr24MxQzZ8bz3k5lVDuy1k6zw6Frjw4fcslFeO0NQzp8/WYsiLumfPeW/S2K4VsmJmYlGH2gfQBUo8tGLrPDAm/6jSjWnLxaCaxg2b7W2HblXAI1ML8UxnFq2QAH2p0Snlumcs75DRGlpDQ0Laqy9678QAd216OFI3FM9i/NMXmfyyZOxM7zNWDnjl28xxYha1PP3ZJB/iCcvVVUTghCIwVT/AUTjFszz1L78mBmhYE5vTAV0/+62aVVQb7pbbrh6l1TnbcUOGZStdtSIz0ZkTWXRYMXSrnjY+zWRW0eFxwu6EHsCTqR9P2HlZOqdOs2ycBHL4QawaE3fIpy0gh0=
