language: python
python: 3.7.2
dist: xenial
sudo: true
install:
- pip install -r requirements.txt
- pip install pytest pytest-cov
script:
- python -m pytest --cov-report term-missing --cov-config .coveragerc --cov=./ ./tests/unit
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; sudo apt-get install -y docker-compose && docker-compose run web python3.7 -m pytest --cov-report term-missing --cov-config
  .coveragerc --cov=./ ./tests/integration; fi
notifications:
  email:
    on_success: never
    on_failure: change
before_install:
- openssl aes-256-cbc -K $encrypted_3256ad516826_key -iv $encrypted_3256ad516826_iv
  -in db_env.list.enc -out ./db_env.list -d
- openssl aes-256-cbc -K $encrypted_3256ad516826_key -iv $encrypted_3256ad516826_iv
  -in env.list.enc -out ./env.list -d
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_3256ad516826_key
  -iv $encrypted_3256ad516826_iv -in deploy_key.enc -out ~/deploy_key -d; fi
before_deploy:
- bash docker_push
deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
